services:
    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
            PGADMIN_DEFAULT_PASSWORD: '${POSTGRES_PASSWORD}'
            PGADMIN_DISABLE_POSTFIX: '${PGADMIN_DISABLE_POSTFIX}'
            POSTGRES_DB: '${POSTGRES_DB}'
            POSTGRES_USER: '${POSTGRES_USER}'
            ALLOW_SAVE_TUNNEL_PASSWORD: 'True,'
        ports:
            - '${FORWARD_PGADMIN_PORT:-80}:80'
        volumes:
            - './docker/config/pgadmin/servers.json:/pgadmin4/servers.json'
        networks:
            - frankenphp
        depends_on:
            - postgres
    postgres:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_DB: '${POSTGRES_DB}'
        ports:
            - '${FORWARD_POSTGRES_PORT:-5432}:5432'
        volumes:
            - 'frankenphp:/var/lib/postgresql/data'
            - './docker/postgres.conf:/etc/postgresql/postgresql.conf'
        networks:
            - frankenphp
    mailpit:
        image: axllent/mailpit
        restart: unless-stopped
        volumes:
            - './data:/data'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - frankenphp
    frankenphp:
        build:
            context: ./docker/
        ports:
            - "443:443"
            - "443:443/udp"
            - "80:80"
        networks:
            - frankenphp
        environment:
            FRANKENPHP_CONFIG:  "worker ./worker.php"
        volumes:
            - './webroot:/app/public'
            - '.:/app'
            - './config:/app/config'
networks:
    frankenphp:
        driver: bridge
        enable_ipv6: false
volumes:
    frankenphp:
        driver: local

